# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72
env: flex
runtime_config:
    document_root: .
env_variables:
    APP_LOG: errorlog
    GOOGLE_STORAGE_BUCKET: "mysql-php-test-2020.appspot.com"
    MYSQL_USER: "<ishtiyak>"
    MYSQL_PASSWORD: "<admin123>"
    MYSQL_DSN: "mysql:dbname=demo;unix_socket=/cloudsql/mysql-php-test-2020:asia-south1:testsql1"
beta_settings:
    cloud_sql_instances: "mysql-php-test-2020:asia-south1:testsql1"

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php
